name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7.1", "3.8", "3.9", "3.10"]
        poetry-version: [1.1.11]
        os: [ubuntu-latest] # , macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Install dependencies
      run: poetry install -E ci
    - name: Formatting
      run: |
        poetry run isort -c openweb
        poetry run black --check openweb
    - name: Code style
      run: |
        poetry run isort -c openweb
        poetry run black --check openweb
        poetry run flake8
        poetry run pylint openweb
        poetry run mypy openweb
    - name: Security
      run: |
        poetry run bandit -r openweb/ -x *_test.py
    - name: Tests
      run: |
        poetry run pytest --cov
    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
        COVERALLS_PARALLEL: true
      run: |
        poetry run coveralls --service=github

  coveralls:
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --service=github --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}